version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpadmin
      MYSQL_PASSWORD: Testing123!
      MYSQL_ROOT_PASSWORD: Testing123!
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80

    volumes:
      - ./wp-content:/var/www/html/wp-content

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpadmin
      WORDPRESS_DB_PASSWORD: Testing123!
      WORDPRESS_DB_NAME: wpdb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - 8181:80

    volumes:
     - /sessions

    environment:
     # PMA_ARBITRARY: 1
     MYSQL_USERNAME: wpadmin
     MYSQL_ROOT_PASSWORD: Testing123!
