version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_PORT}:3306

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USERNAME}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_ROOT_PASSWORD}
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'

  web:
    build:
      context: ./web
      dockerfile: Dockerfile

    restart: always
    ports:
      - ${WORDPRESS_PORT}:80

    volumes:
      # WordPress content - themes etc
      - ./web/wp-content:/var/www/html/wp-content
      # SPA Application (Apache configured to point to this with an alias)
      - ./web/app/dist:/var/www/app
      # Global container Apache configuration
      - ./web/apache2.conf:/etc/apache2/apache2.conf
      # Apache specific site configurations
      - ./web/sites-available:/etc/apache2/sites-available

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  api:
    # Defining the api build verbose - in case we want alternate Dockerfile configs
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${API_PORT}:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - ${MYADMIN_PORT}:80

    volumes:
     - /sessions

    environment:
     # PMA_ARBITRARY: 1
     PMA_USER: ${WORDPRESS_DB_USERNAME}
     PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}