version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_PORT}:3306

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USERNAME}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_ROOT_PASSWORD}
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    image: wordpress
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80

    volumes:
      - ./wp-content:/var/www/html/wp-content

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - ${MYADMIN_PORT}:80

    volumes:
     - /sessions

    environment:
     # PMA_ARBITRARY: 1
     PMA_USER: ${WORDPRESS_DB_USERNAME}
     PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}
